# Generated by Django 2.1.7 on 2019-05-19 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20190520_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='user_cart',
            name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User_cart',
        ),
    ]
