# Generated by Django 2.1.3 on 2019-05-20 23:47

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20190520_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_orders',
            fields=[
                ('id', models.UUIDField(default=ecommerce.models.generateUUID, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chekout', to='ecommerce.User_cart')),
            ],
        ),
    ]
