# Generated by Django 2.1.3 on 2019-05-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20190521_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_orders',
            name='products',
        ),
        migrations.AddField(
            model_name='product_orders',
            name='product',
            field=models.ManyToManyField(related_name='products_order', to='ecommerce.Product'),
        ),
        migrations.AddField(
            model_name='product_orders',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_order', to='ecommerce.Member'),
        ),
    ]
