# Generated by Django 2.1.3 on 2019-05-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20190521_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orders',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
