# Generated by Django 2.1.3 on 2019-05-21 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_product_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_orders',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
