# Generated by Django 2.1.3 on 2019-05-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20190521_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_orders',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
