# Generated by Django 2.1.3 on 2019-05-21 12:59

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20190521_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orders',
            name='order_id',
            field=models.UUIDField(default=ecommerce.models.generateUUID, editable=False),
        ),
    ]
