# Generated by Django 2.1.3 on 2019-05-21 18:50

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_product_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_orders',
            name='order_id',
            field=models.UUIDField(default=ecommerce.models.generateUUID, editable=False, unique=True),
        ),
    ]
