# Generated by Django 2.1.3 on 2019-05-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20190521_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='billing_first_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='billing_last_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
