# Generated by Django 2.1.3 on 2019-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_auto_20190523_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='billing_email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
