# Generated by Django 2.1.3 on 2019-05-22 21:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_member_billing_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orders',
            name='prods_qty',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
